version: "3"
services:
  qa-test:
    image: ciene:latest
    environment:
      - AWS_ACCESS_KEY_ID= ${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY= ${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ./target:/target

  chrome:
    image: selenium/node-chrome:4.0.0-20211025
    shm_size: 2gb
    restart: always
    depends_on:
      - selenium-hub
    deploy:
      replicas: 3
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  edge:
    image: selenium/node-edge:4.0.0-20211025
    shm_size: 2gb
    restart: always
    depends_on:
      - selenium-hub
    deploy:
      replicas: 3
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_GRID_URL=http://localhost:4444

  firefox:
    image: selenium/node-firefox:4.0.0-20211025
    shm_size: 2gb
    restart: always
    depends_on:
      - selenium-hub
    deploy:
      replicas: 3 
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_GRID_URL=http://localhost:4444

  selenium-hub:
    image: selenium/hub:4.0.0-20211025
    container_name: selenium-hub
    restart: always
    healthcheck:  
      interval: 5m
      timeout: 30s
      retries: 1
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"