version: '2.0'
services:
  selenium-hub:
    image: selenium/hub:latest
    networks:
      - selenium_test
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:latest
    networks:
      - selenium_test
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - NODE_MAX_INSTANCES=5
      - NODE_MAX_SESSION=5
    restart: always

  firefox:
    image: selenium/node-firefox:latest
    networks:
      - selenium_test
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - NODE_MAX_INSTANCES=5
      - NODE_MAX_SESSION=5
    restart: always

networks:
  selenium_test:
    driver: bridge