########################################################################################################################
# Customers variables file
# Contains variables
#  - related to specific customer
############################################# Customer properties ######################################################

# Define the customer
# We can add customer_identity and other information related to customer, so remove from environment properties
########################################################################################################################

######################################################## AP-INT ########################################################
ap-int:
  cloud_reference_name: apriori-internal

  ci-connect:
    customer_name: aPrioriInternal_Customer
    agent_type: windchill
    windchill:
      port: 8811
      connector: WC-consvwc02
      agent_name: e1663f08-f660-4969-aeaf-b89d15624ae3_Agent
    teamcenter:
      port: 8810
      connector: TC-consvtc12
      agent_name: c3101e82-4cfc-4a3b-a341-ee53c3f05f55_Agent
    filesystem:
      port: 8809
      connector: FS-conqcic01
    enovia:
      port: 8808
      connector: EN-consvwc02

  ### Customer configurations for specific for environment ###
  # name should be the same with environment name
  qa-test:
    user_staff_identity: AK8JJH37GM54

  int-core:
    user_staff_identity: 8GFDIG229629


  staging:
    customer_identity: 7G0JGBE2N4GM
    user_staff_identity: 6AHL1HHGB15E
    token_subject: 2b68

  local:
    user_staff_identity: 4N630F61FGNG


  development:
    customer_identity: 212B5ABD2F6C
  ###########################################################


######################################################## GADGETS #######################################################
gadgets:
  cloud_reference_name: gadgets

########################################################################################################################


######################################################## WIDGETS #######################################################
widgets:
  cloud_reference_name: widgets

  ci-connect:
    customer_identity: 52IC4D3J98GN
    customer_name: 130cf4de-82aa-460c-9991-014a63b7dc20_Customer
    agent_type: windchill
    windchill:
      port: 8807
      connector: WC-consvwc02
      agent_name: 59cf01bd-b45c-4252-a94c-e433fbc342fa_Agent

  ### Customer configurations for specific for environment ###
  # name should be the same with environment name
  staging:
    customer_identity: 2F265BC1MKAB
  ###########################################################

########################################################################################################################


####################################################### SPROCKETS ######################################################
sprockets:
  qa-test:
    token_subject: c8fc

########################################################################################################################

