########################################################################################################################
# If there is no variable for this environment,
# check global-config.yml file,
# if the value in the file is missing or does not match the required one, add it to the current file
######################################################## QA-TEST #######################################################
qa-test:
  name: qa-test
  aws_parameter_store_name: qa-test
  base_url: https://na-1-install.${${customer}.cloud_reference_name}.qa-test.apriori.net/
  multi_tenant_installation_name: core-na-1 - ${${deployment}.name}

  admin:
    ui_url: ${base_url}apriori/login
    welcome_page_text: CI-Admin
    login_locator: //button[@id='1-submit']
    login_title_locator: //*[@class='auth0-lock-name']

  cds:
    apriori_core_services_installation_identity: 7CAIEIB9J1NI
    apriori_cloud_home_identity: 1J8M416FBJBK
    appro_application_identity: 1J8M416FBJ94
    apriori_production_deployment_identity: 7FLINC95H3A3
    cia_application_identity: 1J8M416FBJCD
    ap_workspace_application_identity: H337GKD0M01A
    cir_application_identity: 1J8M416FBJDE
    acs_application_identity: DD4356A476DC
    identity_role: 67J517C9L763

  reports:
    ui_url: ${base_url}jasperserver-pro/
    on_prem_vm_url: https://conqbaci01/jasperserver-pro/
    username_locator: //input[@type='email']
    login_locator: //button[@id='1-submit']
    welcome_page_text: CI-Admin aPriori Internal
    login_title_locator: //*[@class='auth0-lock-name']
    failed_login_message: WE'RE SORRY, SOMETHING WENT WRONG WHEN ATTEMPTING TO LOG IN.

########################################################################################################################

######################################################## INT-CORE ######################################################
int-core:
  name: int-core
  aws_parameter_store_name: int-blue
  base_url: https://cost.${${customer}.cloud_reference_name}.int.apriori.net/
  multi_tenant_installation_name: Core Services
  secret_key: 65J1ID2B6LDG


  core_service_url_template: core.int.apriori.net/
  deployment_url_template: core.int.apriori.net/

  admin:
    ui_url: ${qa-test.base_url}apriori/login

  bcs:
    report_identity: 50A4DFJF3NC7
    reportType_identity: 0J3JMAA4MCAJ
    part_identity: 6E5GDN0CHB95
    batch_identity: 6N92EN8EHM52

  cds:
    apriori_core_services_installation_identity: 70EGN68B5CMH
    apriori_cloud_home_identity: 1J8M416FBJBK
    appro_application_identity: 1J8M416FBJ94
    apriori_production_deployment_identity: H337GKD0LA0N
    cia_application_identity: 1J8M416FBJCD
    identity_role: 67J517C9L762

  reports:
    ui_url: ${qa-test.base_url}jasperserver-pro/

########################################################################################################################


######################################################## STAGING #######################################################
staging:
  name: staging
  aws_parameter_store_name: stage
  base_url: https://na-1-install.${${customer}.cloud_reference_name}.staging.apriori.net/
  multi_tenant_installation_name: ${${deployment}.name} na-1
  #  TODO: uncomment for staging local run
  secret_key: K6JWVF8KV884

  cds:
    apriori_core_services_installation_identity: 2GIKI57NE7M4
    appro_application_identity: 1J8M416FBJ94
    cia_application_identity: 1J8M416FBJCD
    cir_application_identity: 1J8M416FBJDE
    acs_application_identity: DD4356A476DC
    apriori_production_deployment_identity: 7G0JGBE2N4GN
    apriori_cloud_home_identity: 1J8M416FBJDE
    identity_role: 7G0JGBE2N2GE

  reports:
    ui_url: ${base_url}jasperserver-pro/

########################################################################################################################

######################################################## PRODUCTION #####################################################
prod:
  name: production
  aws_parameter_store_name: prod
  core_service_url_template: ${default.aws_region}.apriori.net/

########################################################################################################################

######################################################## On Prem #######################################################
onprem:
  base_url: walqbaci01/
  name: onprem
  deployment_url_template: ${base_url}
  users_csv_file: onprem-users.csv

########################################################################################################################


######################################################## MIGRATION #####################################################
migration:
  name: migration
  aws_parameter_store_name: mig-21-1
  secret_key: X0V4XXK2SF87

########################################################################################################################


######################################################## MIGRATION-PREVIEW #############################################
migration-preview:
  name: migration-preview
  aws_parameter_store_name: mig-21-1
  secret_key: X0V4XXK2SF87

########################################################################################################################


######################################################## DEV-CFIRST ####################################################
dev-cfirst:
  aws_parameter_store_name: dev-cfirst
  secret_key: 9FRTP0TSZO5W

########################################################################################################################


######################################################## LOCAL #########################################################
local:
  ap_user_context:
  base_url: http://localhost
  name: local
  secret_key: O85XMATZEMBO
  multi_tenant_installation_name: US 1

  admin:
    ui_url: ${local.base_url}/apriori/login

  ats:
    api_url: ${local.base_url}:8805/
    token_username: qa-automation-01
    token_email: qa-automation-01@apriori.com

  bcs:
    api_url: ${local.base_url}:8810/

  cas:
    ui_url: ${local.base_url}:3002/
    api_url: ${local.base_url}:8818/

  cds:
    api_url: ${local.base_url}:8808/
    apriori_core_services_installation_identity: 70EGN68B5CMH
    apriori_cloud_home_identity: 1J8M416FBJBK
    appro_application_identity: 1J8M416FBJ94
    apriori_production_deployment_identity: H337GKD0LA0N
    identity_role: H337GKD0L80E
    cia_application_identity: 1J8M416FBJCD
    cir_application_identity: 1J8M416FBJDE
    acs_application_identity: DD4356A476DC

  cidapp:
    ui_url: ${local.base_url}:3003/
    api_url: ${local.base_url}:8813/

  cus:
    api_url: ${local.base_url}:8828/

  cis:
    ui_url: ${local.base_url}:3004/
    api_url: ${local.base_url}:8815/

  css:
    ui_url: ${local.base_url}:8802
    api_url: ${local.base_url}:8802/

  fms:
    api_url: ${local.base_url}:8806/

  nts:
    api_url: ${local.base_url}:8807/

  reports:
    ui_url: ${local.base_url}jasperserver-pro/login.html

  sds:
    api_url: ${local.base_url}:8811/

  vds:
    api_url: ${local.base_url}:8812/

  cloud:
    ui_url: ${local.base_url}:3001/

  ach:
    api_url: ${local.base_url}:8800/

  cmp:
    api_url: ${local.base_url}:8830/

  igs:
    api_url: ${local.base_url}:8899/

  dds:
    api_url: ${local.base_url}:8817/

  qms:
    api_url: ${local.base_url}:8821/

  qds:
    api_url: ${local.base_url}:8814/

  edc:
    ui_url: ${local.base_url}:3000/
    api_url: ${local.base_url}:8803/

  bcm:
    api_url: ${local.base_url}:8832/

  gcd:
    api_url: ${local.base_url}:8829/

########################################################################################################################

######################################################## DEVELOPMENT ###################################################
development:
  name: development
  aws_parameter_store_name: development
  base_url: https://cloud.na-1.development.apriori.net/
  base_url_reports: https://na-1-install.apriori-internal.development.apriori.net/
  multi_tenant_installation_name: ${${deployment}.name}
  secret_key: O85XMATZEMBO
  user_identity: 4N630F61FGNG

  cds:
    apriori_core_services_installation_identity: ND11N124DE4F
    apriori_cloud_home_identity: 1J8M416FBJBK
    appro_application_identity: 1J8M416FBJ94
    apriori_production_deployment_identity: N6LFCKE8GL94
    cia_application_identity: 1J8M416FBJCD
    cir_application_identity: 1J8M416FBJDE
    acs_application_identity: DD4356A476DC
    identity_role: 67J517C9L763

  reports:
    ui_url: ${base_url_reports}jasperserver-pro/

########################################################################################################################
