########################################################################################################################
# If there is no variable for this environment,
# check global-config.yml file,
# if the value in the file is missing or does not match the required one, add it to the current file
######################################################## QA-TEST #######################################################
qa-test:
  name: qa-test
  aws_parameter_store_name: qa-test
  base_url: https://na-1-install.${customer}.qa-test.apriori.net/

  admin:
    ui_url: ${base_url}apriori/login
    welcome_page_text: CI-Admin
    login_locator: //button[@id='1-submit']
    login_title_locator: //*[@class='auth0-lock-name']

  cds:
    apriori_core_services_installation_identity: 7CAIEIB9J1NI
    apriori_production_deployment_identity: 7FLINC95H3A3
    identity_role: 67J517C9L763

  reports:
    ui_url: ${base_url}jasperserver-pro/
    on_prem_vm_url: https://conqbaci01/jasperserver-pro/
    username_locator: //input[@type='email']
    login_locator: //button[@id='1-submit']
    welcome_page_text: CI-Admin aPriori Internal
    login_title_locator: //*[@class='auth0-lock-name']
    failed_login_message: WE'RE SORRY, SOMETHING WENT WRONG WHEN ATTEMPTING TO LOG IN.

########################################################################################################################

######################################################## STAGING #######################################################
staging:
  name: staging
  aws_parameter_store_name: stage
  base_url: https://na-1-install.${customer}.staging.apriori.net/
  #  TODO: uncomment for staging local run
  secret_key: K6JWVF8KV884

  cds:
    apriori_core_services_installation_identity: 2GIKI57NE7M4
    apriori_production_deployment_identity: 7G0JGBE2N4GN
    identity_role: 7G0JGBE2N2GE

  reports:
    ui_url: ${base_url}jasperserver-pro/

########################################################################################################################

######################################################## PRODUCTION #####################################################
prod:
  name: production
  aws_parameter_store_name: prod
  core_service_url_template: ${default.aws_region}.apriori.net/

########################################################################################################################

######################################################## On Prem #######################################################
onprem:
  base_url: walqbaci01/
  name: onprem
  deployment_url_template: ${base_url}
  users_csv_file: onprem-users.csv

########################################################################################################################

######################################################## DEV-CFIRST ####################################################
dev-cfirst:
  aws_parameter_store_name: dev-cfirst
  secret_key: 9FRTP0TSZO5W

########################################################################################################################

######################################################## LOCAL #########################################################
local:
  ap_user_context:
  base_url: http://localhost
  name: local
  secret_key: O85XMATZEMBO
  #multi_tenant_installation_name: US 1

  admin:
    ui_url: ${local.base_url}/apriori/login

  ats:
    api_url: ${local.base_url}:8805/
    token_username: qa-automation-01
    token_email: qa-automation-01@apriori.com

  bcs:
    api_url: ${local.base_url}:8810/

  cas:
    ui_url: ${local.base_url}:3002/
    api_url: ${local.base_url}:8818/

  cds:
    api_url: ${local.base_url}:8808/
    apriori_core_services_installation_identity: 70EGN68B5CMH
    apriori_production_deployment_identity: H337GKD0LA0N
    identity_role: H337GKD0L80E

  cidapp:
    ui_url: ${local.base_url}:3003/
    api_url: ${local.base_url}:8813/

  cus:
    api_url: ${local.base_url}:8828/

  cis:
    ui_url: ${local.base_url}:3004/
    api_url: ${local.base_url}:8815/

  css:
    ui_url: ${local.base_url}:8802
    api_url: ${local.base_url}:8802/

  fms:
    api_url: ${local.base_url}:8806/

  nts:
    api_url: ${local.base_url}:8807/

  reports:
    ui_url: ${local.base_url}jasperserver-pro/login.html

  sds:
    api_url: ${local.base_url}:8811/

  vds:
    api_url: ${local.base_url}:8812/

  cloud:
    ui_url: ${local.base_url}:3001/

  ach:
    api_url: ${local.base_url}:8800/

  cmp:
    api_url: ${local.base_url}:8830/

  igs:
    api_url: ${local.base_url}:8899/

  dds:
    api_url: ${local.base_url}:8817/

  qms:
    api_url: ${local.base_url}:8821/

  qds:
    api_url: ${local.base_url}:8814/

  edc:
    ui_url: ${local.base_url}:3000/
    api_url: ${local.base_url}:8803/

  bcm:
    api_url: ${local.base_url}:8832/

  gcd:
    api_url: ${local.base_url}:8829/

########################################################################################################################

######################################################## DEVELOPMENT ###################################################
development:
  name: development
  aws_parameter_store_name: development
  base_url: https://cloud.na-1.development.apriori.net/
  base_url_reports: https://na-1-install.apriori-internal.development.apriori.net/
  secret_key: O85XMATZEMBO
  user_identity: 4N630F61FGNG

  cds:
    apriori_core_services_installation_identity: ND11N124DE4F
    apriori_production_deployment_identity: N6LFCKE8GL94
    identity_role: 67J517C9L763

  reports:
    ui_url: ${base_url_reports}jasperserver-pro/

########################################################################################################################
