def buildInfo
def buildInfoFile = "build-info.yml"
def timeStamp = new Date().format('yyyyMMddHHmmssSSS')
def javaOpts = ""
def url
def threadCount
def browser
def customer
def testSuite
def users_csv_file
def default_aws_region
def folder
def addJavaOpts
def number_of_parts
def parts_csv_file
def agent_type
def nexus_repository
def nexus_version
def custom_install
def connector
def environment = [profile: 'development', region: 'us-east-1']
def ecrDockerRegistry = '563229348140.dkr.ecr.us-east-1.amazonaws.com/apriori-qa'

pipeline {
    agent {
        label "automation"
    }

    stages {
        stage("Initialize") {
            steps {
                echo "Initializing.."
            }
        }

        stage("Build") {
            steps {
                echo "Building..."
                script {
                    def registryPwd = registry_password("${environment.profile}", "${environment.region}")
                    sh "docker login -u AWS -p ${registryPwd} ${ecrDockerRegistry}"
                    sh """
                         docker build \
                             --no-cache \
                             --target build \
                             --tag ${buildInfo.name}-test-${timeStamp}:latest \
                             --label \"build-date=${timeStamp}\" \
                             --label qa-automation \
                             --build-arg FOLDER=${folder} \
                             --build-arg MODULE=${MODULE} \
                             .
                     """
                }
            }
        }

        stage("Test") {
            steps {
                echo "Testing..."
            }
        }

        stage("Extract Test Results") {
            steps {
                // Copy out build/test artifacts.
                echo "Extract Test Results.."
                publishHTML(target: [
                        allowMissing         : false,
                        alwaysLinkToLastBuild: false,
                        keepAll              : true,
                        reportDir            : '',
                        reportFiles          : 'index.html',
                        reportName           : "test-report.html"
                ])
            }
        }
    }

    post {
        always {
            echo "Cleaning up.."
            }
        }
    }
}