########################################################################################################################
# Customers variables file
# Contains variables
#  - related to specific customer
############################################# Customer properties ######################################################

# Define the customer
# We can add customer_identity and other information related to customer, so remove from environment properties
########################################################################################################################

######################################################## AP-INT #######################################################
ap-int:
  token_subject: 4127
  ci-connect:
    customer_identity: 6C1F8C1D4D75
    agent_api_url: http://conqscic02.fbc.com:8811/
    plm_agent_id: e1663f08-f660-4969-aeaf-b89d15624ae3_Agent
    customer_name: aPrioriInternal_Customer

########################################################################################################################


######################################################## GADGETS #######################################################
gadgets:
  token_subject: 247f

########################################################################################################################


######################################################## WIDGETS #######################################################
widgets:
  token_subject: 739e
  ci-connect:
    customer_identity: 52IC4D3J98GN
    agent_api_url: http://conqsct01:8817/
    plm_agent_id: 3e5056e2-dc98-4ef4-a2d3-e6f7b97147db_Agent
    customer_name: 130cf4de-82aa-460c-9991-014a63b7dc20_Customer

########################################################################################################################


####################################################### SPROCKETS ######################################################
sprockets:
  token_subject: c8fc

########################################################################################################################