########################################################################################################################
# Customers variables file
# Contains variables
#  - related to specific customer
############################################# Customer properties ######################################################

# Define the customer
# We can add customer_identity and other information related to customer, so remove from environment properties
########################################################################################################################

######################################################## AP-INT ########################################################
ap-int:
  cloud_reference_name: apriori-internal
  # depends on customer_aws_account_type property from environment in environments-config.yml file, or default section in global-config.yml file
  staging:
    token_subject: e63c

  ci-connect:
    customer_identity: 6C1F8C1D4D75
    customer_name: aPrioriInternal_Customer
######################################################## GADGETS #######################################################
gadgets:
  cloud_reference_name: gadgets
########################################################################################################################


######################################################## WIDGETS #######################################################
widgets:
  cloud_reference_name: widgets

  ci-connect:
    customer_identity: 52IC4D3J98GN
    customer_name: 130cf4de-82aa-460c-9991-014a63b7dc20_Customer
########################################################################################################################


####################################################### SPROCKETS ######################################################
sprockets:

########################################################################################################################

