########################################################################################################################
# If there is no variable for this environment,
# check global-config.yml file,
# if the value in the file is missing or does not match the required one, add it to the current file
######################################################## INT-CORE ########################################################
int-core:
  base_url: https://cost.apriori-internal.int.apriori.net/
  customer_identity: H337GKD0LA0M
  name: int-core
  secret_key: 65J1ID2B6LDG
  user_identity: 8GFDIG229629

  admin:
    ui_url: ${int-core.base_url}apriori/login

  ats:
    api_url: https://ats.core.int.apriori.net/

  bcs:
    api_url: https://bcs.core.int.apriori.net/
    report_identity: 50A4DFJF3NC7
    reportType_identity: 0J3JMAA4MCAJ
    part_identity: 6E5GDN0CHB95
    batch_identity: 6N92EN8EHM52

  ci-connect:
    ui_url: https://ci-connect.core.int.apriori.net/

  cidapp:
    ui_url: https://cid.core.int.apriori.net/
    api_url: https://cid-api.core.int.apriori.net/

  cis:
    ui_url: https://cis.core.int.apriori.net/
    api_url: https://cis-api.core.int.apriori.net/

  cas:
    ui_url: https://cas.core.int.apriori.net/
    api_url: https://cas-api.core.int.apriori.net/

  cds:
    api_url: https://cds.core.int.apriori.net/
    apriori_core_services_installation_identity: 70EGN68B5CMH
    apriori_cloud_home_identity: 1J8M416FBJBK
    appro_application_identity: 1J8M416FBJ94
    apriori_production_deployment_identity: H337GKD0LA0N
    cia_application_identity: 1J8M416FBJCD
    automation_user_identity02: 9671G0C4GNK2
    automation_user_identity03: 775K40H47HEF
    identity_role: 67J517C9L762

  css:
    api_url: https://css.core.int.apriori.net/

  edc:
    ui_url: https://edc.core.int.apriori.net/
    api_url: https://edc-api.core.int.apriori.net/

  fms:
    api_url: https://fms.core.int.apriori.net/

  nts:
    api_url: https://nts.core.int.apriori.net/

  reports:
    ui_url: https://cost.apriori-internal.int.apriori.net/jasperserver-pro/

  sds:
    api_url: https://sds.core.int.apriori.net/

  vds:
    api_url: https://vds.core.int.apriori.net/



######################################################## On Prem ########################################################
onprem:
  name: onprem

  bcs:
    report_identity: 50A4DFJF3NC7
    reportType_identity: 0J3JMAA4MCAJ
    part_identity: 6E5GDN0CHB95
    batch_identity: 6N92EN8EHM52

  cds:
    apriori_core_services_installation_identity:
    apriori_cloud_home_identity: 1J8M416FBJBK
    appro_application_identity: 1J8M416FBJ94
    apriori_production_deployment_identity:
    cia_application_identity: 1J8M416FBJ94
    automation_user_identity02: 9671G0C4GNK2
    automation_user_identity03: 775K40H47HEF
    identity_role: 67J517C9L762

######################################################## STAGING ########################################################
staging:
  ap_user_context:
  base_url: https://na-1-v22-1-demo.apriori-internal.staging.apriori.net/
  customer_identity: 7G0JGBE2N4GM
  secret_key: K6JWVF8KV884
  user_identity: 6AHL1HHGB15E

  cds:
    apriori_core_services_installation_identity: 2GIKI57NE7M4
    appro_application_identity: 1J8M416FBJ94
    cia_application_identity: 1J8M416FBJCD
    apriori_production_deployment_identity: 7G0JGBE2N4GN
    apriori_cloud_home_identity: 1J8M416FBJDE
    automation_user_identity02: 6AHL3EHF264K
    automation_user_identity03: 1K2LKIB78J6A
    identity_role: 7G0JGBE2N2GE

  bcs:
    api_url: https://bcs.us.staging.apriori.net/

######################################################## LOCAL ########################################################
local:
  ap_user_context:
  base_url: http://localhost
  name: local
  secret_key: 65J1ID2B6LDG

  admin:
    ui_url: ${local.base_url}apriori/login

  ats:
    api_url: ${local.base_url}:8805/
    token_username: qa-automation-01
    token_email: qa-automation-01@apriori.com

  bcs:
    api_url: ${local.base_url}:8810/

  cas:
    ui_url: ${local.base_url}:3002/
    api_url: ${local.base_url}:8818/

  cds:
    api_url: ${local.base_url}:8808/
    apriori_core_services_installation_identity: 70EGN68B5CMH
    apriori_cloud_home_identity: 1J8M416FBJBK
    appro_application_identity: 1J8M416FBJ94
    apriori_production_deployment_identity: H337GKD0LA0N
    identity_role: H337GKD0L80E

  cidapp:
    ui_url: ${local.base_url}:3003/
    api_url: ${local.base_url}:8813/

  cus:
    api_url: ${local.base_url}:8828/

  cis:
    ui_url: ${local.base_url}:3004/

  css:
    ui_url: ${local.base_url}:8802
    api_url: ${local.base_url}:8802/

  fms:
    api_url: ${local.base_url}:8806/

  nts:
    api_url: ${local.base_url}:8807/

  reports:
    ui_url: ${local.base_url}jasperserver-pro/login.html

  sds:
    api_url: ${local.base_url}:8811/

######################################################## QA-TEST ########################################################
qa-test:
  application_name: cid
  base_url: https://na-1-v23-1-demo.apriori-internal.qa-test.apriori.net/
  customer_identity: 6C1F8C1D4D75
  deployment_name: production
  installation_name: core-na-1 - 23 production deployment
  name: qa-test
  secret_key: PG9E795ML3P4
  user_identity: AK8JJH37GM54

  admin:
    ui_url: ${qa-test.base_url}apriori/login

  cds:
    apriori_core_services_installation_identity: 7GFDL6LCI5N4
    apriori_cloud_home_identity: 1J8M416FBJBK
    appro_application_identity: 1J8M416FBJ94
    apriori_production_deployment_identity: 7FLINC95H3A3
    cia_application_identity: 1J8M416FBJCD
    automation_user_identity02: AKC81M50KGFE
    automation_user_identity03: AFMMDK0IJHG4
    identity_role: 67J517C9L763

  ci-connect:
    second_page_starting_range_number: 26
    default_connector: Automation - NA - WC
    agent_api_authorization_key: DogCatMonkey
    agent_api_url: http://conqsct01:8811/
    plm_agent_id: e1663f08-f660-4969-aeaf-b89d15624ae3_Agent
    plm_wc_api_url: https://consvwc02.fbc.com/
    plm_wc_api_token: d2NhZG1pbjp0ZXN0MTIzIw==
    ap-int:
      customer_identity: 6C1F8C1D4D75
      agent_api_url: http://conqsct01:8811/
      plm_agent_id: e1663f08-f660-4969-aeaf-b89d15624ae3_Agent
      customer_name: aPrioriInternal_Customer
    widgets:
      customer_identity: 52IC4D3J98GN
      agent_api_url: http://conqsct01:8817/
      plm_agent_id: 3e5056e2-dc98-4ef4-a2d3-e6f7b97147db_Agent
      customer_name: 130cf4de-82aa-460c-9991-014a63b7dc20_Customer


######################################################## QA-CID-PERF ########################################################
qa-cid-perf:
  base_url: https://demo.apriori-internal.qa-cid-perf.apriori.net/
  customer_identity: 92E1E4E9DFCD
  name: qa-cid-perf
  secret_key: 502M4JBUCE36
  user_identity: 1F7GAI5DLI2B

  cds:
    apriori_core_services_installation_identity: 8E9MK02F4H9F
    apriori_cloud_home_identity: 1J8M416FBJBK
    appro_application_identity: 1J8M416FBJ94
    apriori_production_deployment_identity: CNLKB29B4GN8
    cia_application_identity: 1J8M416FBJCD
    automation_user_identity02: 1F4GF3E20D38
    automation_user_identity03: 1F4HJ2A9GM9C
    identity_role: 67J517C9L763

  ci-connect:
    second_page_starting_range_number: 26
    default_connector: Automation - NA - WC
    agent_api_url: http://conqsct01:8810/
    agent_api_authorization_key: DogCatMonkey

  reports:
    ui_url: ${qa-cid-perf.base_url}jasperserver-pro/login.html


#                                                                                                                              #
#                                                                                                                              #
#                                                                                                                              #
#                                                                                                                              #
######################################################## DO WE NEED IT? ########################################################
#                                                                                                                              #
#                                                                                                                              #
#                                                                                                                              #
#                                                                                                                              #

######################################################## QA-CID-PERF-SANDBOX ########################################################
qa-cid-perf-sandbox:
  base_url: https://demo.apriori-internal.qa-cid-perf.apriori.net/
  customer_identity: 92E1E4E9DFCD
  name: qa-cid-perf-sandbox
  secret_key: 502M4JBUCE36
  user_identity: 1F7GAI5DLI2B

######################################################## QA-CIG-PERF ########################################################
qa-cig-perf:
  base_url: https://demo.apriori-internal.qa-cig-perf.apriori.net/
  customer_identity: C339C55A8155
  name: qa-cig-perf
  user_identity: C339C55A8155
  secret_key: WJIM0HV7Z6U1

  bcs:
    report_identity: 50A4DFJF3NC7
    reportType_identity: 0J3JMAA4MCAJ
    part_identity: 6E5GDN0CHB95
    batch_identity: 6N92EN8EHM52

  cds:
    apriori_core_services_installation_identity:
    apriori_cloud_home_identity: 1J8M416FBJBK
    appro_application_identity: 1J8M416FBJ94
    apriori_production_deployment_identity:
    cia_application_identity: 1J8M416FBJ94
    automation_user_identity02: 9671G0C4GNK2
    automation_user_identity03: 775K40H47HEF
    identity_role: 67J517C9L762

  reports:
    ui_url: ${qa-cig-perf.base_url}jasperserver-pro/login.html

######################################################## QA-20-1 ########################################################
qa-20-1:
  base_url: https://demo.apriori-internal.qa-20-1.apriori.net/
  name: qa-20-1
  secret_key: LZJM8S47H5S8

  admin:
    ui_url: ${qa-20-1.base_url}apriori/login

  ats:
    token_issuer: 2020 R1


######################################################## MIGRATION #####################################################
migration:
#  name: migration
#  customer_identity: 3KED5H5BKN85
#  secret_key: X0V4XXK2SF87

######################################################## MIGRATION-PREVIEW #####################################################
migration-preview:
#  name: migration-preview
#  secret_key: X0V4XXK2SF87



######################################################## DEV-CFIRST ########################################################
dev-cfirst:
  name: dev-cfirst
  base_url: https://cloud.na-1.dev-cfirst.apriori.net/
  secret_key: 9FRTP0TSZO5W

  profile_page: ${dev-cfirst.base_url}user-profile


######################################################## QA-TEST-V22 ########################################################
qa-test-v22:
  application_name: cid
#  customer_identity: 6C1F8C1D4D75
#  deployment_name: production
  installation_name: core-na-1 - 22 production deployment
#  name: qa-test
#  secret_key: PG9E795ML3P4
  user_identity: AK8JJH37GM54

  cds:
    apriori_core_services_installation_identity: 7GFDL6LCI5N4
    apriori_cloud_home_identity: 1J8M416FBJBK
    appro_application_identity: 1J8M416FBJ94
    apriori_production_deployment_identity: 7FLINC95H3A3
    cia_application_identity: 1J8M416FBJCD
    automation_user_identity02: AKC81M50KGFE
    automation_user_identity03: AFMMDK0IJHG4
    identity_role: 67J517C9L763

  ci-connect:
    second_page_starting_range_number: 26
    default_connector: Automation - NA - WC
    agent_api_authorization_key: DogCatMonkey
    agent_api_url: http://conqsct01:8811/
    plm_agent_id: e1663f08-f660-4969-aeaf-b89d15624ae3_Agent
    ap-int:
      customer_identity: 6C1F8C1D4D75
      agent_api_url: http://conqsct01:8811/
      plm_agent_id: e1663f08-f660-4969-aeaf-b89d15624ae3_Agent
      customer_name: aPrioriInternal_Customer
    widgets:
      customer_identity: 52IC4D3J98GN
      agent_api_url: http://conqsct01:8817/
      plm_agent_id: 3e5056e2-dc98-4ef4-a2d3-e6f7b97147db_Agent
      customer_name: 130cf4de-82aa-460c-9991-014a63b7dc20_Customer

######################################################## CIS_SANDBOX ########################################################
cis-sbx:
  aws_region: na-1
  base_url: https://demo.apriori-internal.qa-cid-perf.apriori.net/
  customer_identity: 92E1E4E9DFCD
  name: cis-sbx
  secret_key: 502M4JBUCE36
  user_identity: 1F7GAI5DLI2B

  cidapp:
    api_url: https://cid-api.dev-cis-sbx.apriori.net/
    ui_url:  https://cid.dev-cis-sbx.apriori.net/

  cis:
    ui_url: https://cis.dev-cis-sbx.apriori.net/

  css:
    api_url: https://css.dev-cis-sbx.apriori.net/

######################################################## CIS_QA ########################################################
cis-qa:
  application_name: cis
#  aws_region: na-1
  customer_identity: 6C1F8C1D4D75
#  deployment_name: qa
#  installation_name: cis.na-1-v22-1
#  name: cis-qa
#  secret_key: PG9E795ML3P4
  user_identity: 1F7GAI5DLI2B

######################################################## QA-TEST-SANDBOX ########################################################
qa-test-sandbox:
  application_name: cid
#  customer_identity: 6C1F8C1D4D75
#  deployment_name: production
  installation_name: core-na-1 - 23 production deployment
#  name: qa-test-sandbox
#  secret_key: PG9E795ML3P4
  user_identity: AK8JJH37GM54

  cds:
    apriori_core_services_installation_identity: 7GFDL6LCI5N4
    apriori_cloud_home_identity: 1J8M416FBJBK
    appro_application_identity: 1J8M416FBJ94
    apriori_production_deployment_identity: 7FLINC95H3A3
    cia_application_identity: 1J8M416FBJCD
    automation_user_identity02: AKC81M50KGFE
    automation_user_identity03: AFMMDK0IJHG4
    identity_role: 67J517C9L763

    ######################################################## QA-TEST-V22-SANDBOX ########################################################
qa-test-v22-sandbox:
  application_name: cid
#  customer_identity: 6C1F8C1D4D75
#  deployment_name: production
  installation_name: core-na-1 - 22 production deployment
#  name: qa-test
  secret_key: PG9E795ML3P4
  user_identity: AK8JJH37GM54

  cds:
    apriori_core_services_installation_identity: 7GFDL6LCI5N4
    apriori_cloud_home_identity: 1J8M416FBJBK
    appro_application_identity: 1J8M416FBJ94
    apriori_production_deployment_identity: 7FLINC95H3A3
    cia_application_identity: 1J8M416FBJCD
    automation_user_identity02: AKC81M50KGFE
    automation_user_identity03: AFMMDK0IJHG4
    identity_role: 67J517C9L763

  ats:
    token_issuer: 2021 R1
    token_subject: 4127
    auth_application: CID

  ci-connect:
    second_page_starting_range_number: 26
    default_connector: WC - auto
    agent_api_authorization_key: DogCatMonkey
    agent_api_url: http://conqsct01:8811/
    plm_agent_id: d8a27107-5fcd-468a-a445-d2955409e83b_Agent
    plm_wc_api_url: https://consvwc02.fbc.com/
    plm_wc_api_token: d2NhZG1pbjp0ZXN0MTIzIw==
    ap-int:
      customer_identity: 6C1F8C1D4D75
      agent_api_url: http://conqscic02:8811/
      plm_agent_id: d8a27107-5fcd-468a-a445-d2955409e83b_Agent
      customer_name: aPrioriInternal_Customer