package com.apriori.acs.models.response.acs.artifactproperties;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Data;

@Data
public class TypedMapBeanPropertyInfoMap {
    private PropertyInfoMapItem actionHandler;
    private PropertyInfoMapItem artifact;
    private PropertyInfoMapItem artifactKey;
    private PropertyInfoMapItem artifactObject;
    private PropertyInfoMapItem artifacts;
    private PropertyInfoMapItem axiGrooveFields;
    private PropertyInfoMapLargerItem bendAngleTolerance;
    private PropertyInfoMapItem bundleMessage;
    private PropertyInfoMapItem catalog;
    private PropertyInfoMapItem centroid;
    private PropertyInfoMapLargerItem circularity;
    @JsonProperty("class")
    private PropertyInfoMapItem classItem;
    private PropertyInfoMapItem classOfInterest;
    private PropertyInfoMapItem componentModel;
    private PropertyInfoMapLargerItem concentricity;
    private PropertyInfoMapLargerItem cylindricity;
    private PropertyInfoMapItem data;
    private PropertyInfoMapItem dbgCadKeyText;
    private PropertyInfoMapItem dbgMinGcdVersion;
    private PropertyInfoMapLargerItem diamTolerance;
    private PropertyInfoMapItem distanceUnits;
    private PropertyInfoMapItem editModeStringFormatter;
    private PropertyInfoMapItem firstArtifact;
    private PropertyInfoMapLargerItem flatness;
    private PropertyInfoMapItem formatInfo;
    private PropertyInfoMapItem homogeneous;
    private PropertyInfoMapItem isMolded;
    private PropertyInfoMapItem manualGcdFields;
    private PropertyInfoMapItem menuName;
    private PropertyInfoMapItem minTolerance;
    private PropertyInfoMapItem name;
    private PropertyInfoMapItem objectHolder;
    private PropertyInfoMapItem overrideStatus;
    private PropertyInfoMapLargerItem parallelism;
    private PropertyInfoMapLargerItem perpendicularity;
    private PropertyInfoMapLargerItem positionTolerance;
    private PropertyInfoMapItem predicateManager;
    private PropertyInfoMapLargerItem profileOfSurface;
    private PropertyInfoMapItem rawPropertyValue;
    private PropertyInfoMapItem requested;
    private PropertyInfoMapLargerItem roughness;
    private PropertyInfoMapLargerItem roughnessRz;
    private PropertyInfoMapLargerItem runout;
    private PropertyInfoMapItem selected;
    private PropertyInfoMapItem setupType;
    private PropertyInfoMapItem status;
    private PropertyInfoMapLargerItem straightness;
    private PropertyInfoMapItem stringFormatter;
    private PropertyInfoMapItem subType;
    private PropertyInfoMapItem subTypePicklistValueSupplier;
    private PropertyInfoMapLargerItem surfaceFinishingRate;
    private PropertyInfoMapLargerItem symmetry;
    private PropertyInfoMapLargerItem thickness;
    private PropertyInfoMapLargerItem time;
    private PropertyInfoMapLargerItem tolerance;
    private PropertyInfoMapItem toolTipText;
    private PropertyInfoMapLargerItem totalRunout;
    private PropertyInfoMapItem transferable;
    private PropertyInfoMapItem underlyingBean;
    private PropertyInfoMapItem unitSystem;
    private PropertyInfoMapItem userDefinedSetupAxis;
    private PropertyInfoMapItem userDefinedSetupAxisKey;
    private PropertyInfoMapItem volumeFields;
    private PropertyInfoMapLargerItem volumeRemovalRate;
    private PropertyInfoMapItem weldFields;
}
