
######################################################## DEV-CFIRST ########################################################
dev-cfirst:
  name: dev-cfirst
  base_url: https://cloud.na-1.dev-cfirst.apriori.net/
  secret_key: 9FRTP0TSZO5W

  profile_page: ${dev-cfirst.base_url}user-profile

  cus:
    api_url: https://cus.${default.aws_region}.${env}.apriori.net/
