
######################################################## LOCAL ########################################################
local:
  ap_user_context:
  base_url: http://localhost
  name: local
  secret_key: 65J1ID2B6LDG

  admin:
    ui_url: ${local.base_url}apriori/login

  ats:
    api_url: ${local.base_url}:8805/
    token_username: qa-automation-01
    token_email: qa-automation-01@apriori.com

  bcs:
    api_url: ${local.base_url}:8810/

  cas:
    ui_url: ${local.base_url}:3002/
    api_url: ${local.base_url}:8818/

  cds:
    api_url: ${local.base_url}:8808/
    apriori_core_services_installation_identity: 70EGN68B5CMH
    apriori_cloud_home_identity: 1J8M416FBJBK
    appro_application_identity: 1J8M416FBJ94
    apriori_production_deployment_identity: H337GKD0LA0N
    identity_role: H337GKD0L80E

  cidapp:
    ui_url: ${local.base_url}:3003/
    api_url: ${local.base_url}:8813/

  cus:
    api_url: ${local.base_url}:8828/

  cis:
    ui_url: ${local.base_url}:3004/

  css:
    ui_url: ${local.base_url}:8802
    api_url: ${local.base_url}:8802/

  fms:
    api_url: ${local.base_url}:8806/

  nts:
    api_url: ${local.base_url}:8807/

  reports:
    ui_url: ${local.base_url}jasperserver-pro/login.html

  sds:
    api_url: ${local.base_url}:8811/
