
######################################################## On Prem ########################################################
onprem:
  base_url: https://conqbaci02/
  name: onprem

  admin:
    ui_url: ${onprem.base_url}apriori/login

  bcs:
    report_identity: 50A4DFJF3NC7
    reportType_identity: 0J3JMAA4MCAJ
    part_identity: 6E5GDN0CHB95
    batch_identity: 6N92EN8EHM52

  cds:
    apriori_core_services_installation_identity:
    apriori_cloud_home_identity: 1J8M416FBJBK
    appro_application_identity: 1J8M416FBJ94
    apriori_production_deployment_identity:
    cia_application_identity: 1J8M416FBJ94
    automation_user_identity02: 9671G0C4GNK2
    automation_user_identity03: 775K40H47HEF
    identity_role: 67J517C9L762

  reports:
    ui_url: ${onprem.base_url}jasperserver-pro/
