########################################################################################################################
# If there is no variable for this environment,
# check global-config.yml file,
# if the value in the file is missing or does not match the required one, add it to the current file
######################################################## QA-20-1 ########################################################
qa-20-1:
  base_url: https://demo.apriori-internal.qa-20-1.apriori.net/
  name: qa-20-1
  secret_key: LZJM8S47H5S8

  admin:
    ui_url: ${qa-20-1.base_url}apriori/login

  ats:
    token_issuer: 2020 R1

  reports:
    ui_url: ${qa-20-1.base_url}jasperserver-pro/login.html
