########################################################################################################################
# If there is no variable for this environment,
# check global-config.yml file,
# if the value in the file is missing or does not match the required one, add it to the current file
######################################################## QA-CID-PERF ########################################################
qa-cid-perf:
  env_url_specification: update_this_value_in_environment_file
  base_url: https://demo.apriori-internal.qa-cid-perf.apriori.net/
  customer_identity: 92E1E4E9DFCD
  name: qa-cid-perf
  secret_key: 502M4JBUCE36
  user_identity: 1F7GAI5DLI2B

  admin:
    ui_url: ${qa-cid-perf.base_url}apriori/login

  bcs:
    api_url: https://bcs.na-1-v22-1.qa-cid-perf.apriori.net/
    number_of_parts: 5
  cas:
    ui_url: https://cas.na-1.qa-cid-perf.apriori.net/
    api_url: https://cas-api.na-1.qa-cid-perf.apriori.net/

  cds:
    apriori_core_services_installation_identity: 8E9MK02F4H9F
    apriori_cloud_home_identity: 1J8M416FBJBK
    appro_application_identity: 1J8M416FBJ94
    apriori_production_deployment_identity: CNLKB29B4GN8
    cia_application_identity: 1J8M416FBJCD
    automation_user_identity02: 1F4GF3E20D38
    automation_user_identity03: 1F4HJ2A9GM9C
    identity_role: 67J517C9L763

  ci-connect:
    ui_url: https://ci-connect.na-1-v22-1.qa-cid-perf.apriori.net/
    second_page_starting_range_number: 26
    default_connector: Automation - NA - WC
    agent_api_url: http://conqsct01:8810/
    agent_api_authorization_key: DogCatMonkey

  reports:
    ui_url: ${qa-cid-perf.base_url}jasperserver-pro/login.html
    on_prem_vm_url: https://conqbaci01/jasperserver-pro/
