########################################################################################################################
# If there is no variable for this environment,
# check global-config.yml file,
# if the value in the file is missing or does not match the required one, add it to the current file
######################################################## QA-TEST-SANDBOX ########################################################
qa-test-sandbox:
  env_url_specification: update_this_value_in_environment_file
  application_name: cid
  base_url: https://na-1-v23-1-demo.apriori-internal.qa-test.apriori.net/
  customer_identity: 6C1F8C1D4D75
  deployment_name: production
  installation_name: core-na-1 - 23 production deployment
  name: qa-test-sandbox
  secret_key: PG9E795ML3P4
  user_identity: AK8JJH37GM54

  admin:
    ui_url: ${qa-test.base_url}apriori/login

  ats:
    api_url: https://ats.na-1.qa-test.apriori.net/

  bcs:
    api_url: https://bcs.na-1-v23-1.sandbox.qa-test.apriori.net/
    number_of_parts: 5

  cas:
    ui_url: https://cas.na-1.qa-test.apriori.net/
    api_url: https://cas-api.na-1.qa-test.apriori.net/

  cidapp:
    api_url: https://cid-api.na-1-v23-1.sandbox.qa-test.apriori.net/
    ui_url: https://ci-design.na-1-v23-1.sandbox.qa-test.apriori.net/

  cds:
    api_url: https://cds.na-1.qa-test.apriori.net/
    apriori_core_services_installation_identity: 7GFDL6LCI5N4
    apriori_cloud_home_identity: 1J8M416FBJBK
    appro_application_identity: 1J8M416FBJ94
    apriori_production_deployment_identity: 7FLINC95H3A3
    cia_application_identity: 1J8M416FBJCD
    automation_user_identity02: AKC81M50KGFE
    automation_user_identity03: AFMMDK0IJHG4
    identity_role: 67J517C9L763

  css:
    api_url: https://css.na-1-v23-1.sandbox.qa-test.apriori.net/

  dds:
    api_url: https://dds.na-1-v23-1.sandbox.qa-test.apriori.net/

  dms:
    api_url: https://dms.na-1-v23-1.sandbox.qa-test.apriori.net/

  qms:
    api_url: https://qms.na-1-v23-1.sandbox.qa-test.apriori.net/

  qds:
    api_url: https://qds.na-1-v23-1.sandbox.qa-test.apriori.net/
