########################################################################################################################
# If there is no variable for this environment,
# check global-config.yml file,
# if the value in the file is missing or does not match the required one, add it to the current file
######################################################## QA-TEST ########################################################
qa-test:
  env_url_specification: qa-test
  application_name: cid
  base_url: https://na-1-v23-1-demo.apriori-internal.qa-test.apriori.net/
  customer_identity: 6C1F8C1D4D75
  deployment_name: production
  installation_name: core-na-1 - 23 production deployment
  name: qa-test
  secret_key: PG9E795ML3P4
  user_identity: AK8JJH37GM54

  admin:
    ui_url: ${qa-test.base_url}apriori/login

  bcs:
    api_url: https://bcs-http.na-1-v23-1.${${env}.env_url_specification}.apriori.net/
    number_of_parts: 5

  cas:
    ui_url: https://cas.na-1.qa-test.apriori.net/
    api_url: https://cas-api.na-1.qa-test.apriori.net/

  cds:
    apriori_core_services_installation_identity: 7GFDL6LCI5N4
    apriori_cloud_home_identity: 1J8M416FBJBK
    appro_application_identity: 1J8M416FBJ94
    apriori_production_deployment_identity: 7FLINC95H3A3
    cia_application_identity: 1J8M416FBJCD
    automation_user_identity02: AKC81M50KGFE
    automation_user_identity03: AFMMDK0IJHG4
    identity_role: 67J517C9L763

  ci-connect:
    ui_url: https://ci-connect.na-1-v23-1.qa-test.apriori.net/
    second_page_starting_range_number: 26
    default_connector: Automation - NA - WC
    agent_api_authorization_key: DogCatMonkey
    agent_api_url: http://conqsct01:8811/
    plm_agent_id: e1663f08-f660-4969-aeaf-b89d15624ae3_Agent
    plm_wc_api_url: https://consvwc02.fbc.com/
    plm_wc_api_token: d2NhZG1pbjp0ZXN0MTIzIw==
    ap-int:
      customer_identity: 6C1F8C1D4D75
      agent_api_url: http://conqsct01:8811/
      plm_agent_id: e1663f08-f660-4969-aeaf-b89d15624ae3_Agent
      customer_name: aPrioriInternal_Customer
    widgets:
      customer_identity: 52IC4D3J98GN
      agent_api_url: http://conqsct01:8817/
      plm_agent_id: 3e5056e2-dc98-4ef4-a2d3-e6f7b97147db_Agent
      customer_name: 130cf4de-82aa-460c-9991-014a63b7dc20_Customer

  cidapp:
    api_url: https://cid-api.${default.aws_region}-v23-1.${env}.apriori.net/
    ui_url: https://ci-design.${default.aws_region}-v23-1.${env}.apriori.net/

  css:
    api_url: https://css.${default.aws_region}-v23-1.${env}.apriori.net/

  dds:
    api_url: https://dds.na-1-v23-1.qa-test.apriori.net/

  dms:
    api_url: https://dms.na-1-v23-1.qa-test.apriori.net/

  reports:
    ui_url: ${qa-test.base_url}jasperserver-pro/
    on_prem_vm_url: https://conqbaci01/jasperserver-pro/

  qds:
    api_url: https://qds.na-1-v23-1.qa-test.apriori.net/

  qms:
    api_url: https://qms.na-1-v23-1.qa-test.apriori.net/
