package com.apriori.acs.entity.response.acs.materialsinfo;

import com.apriori.acs.entity.response.acs.genericclasses.GenericExtendedPropertyInfoItem;

import lombok.Data;

@Data
public class PropertyInfoMap {
    private GenericExtendedPropertyInfoItem altName2;
    private GenericExtendedPropertyInfoItem altName3;
    private GenericExtendedPropertyInfoItem altName1;
    private GenericExtendedPropertyInfoItem hardnessSystem;
    private GenericExtendedPropertyInfoItem description;
    private GenericExtendedPropertyInfoItem tensileYieldStrength;
    private GenericExtendedPropertyInfoItem scrapCostPercent;
    private GenericExtendedPropertyInfoItem ultimateTensileStrength;
    private GenericExtendedPropertyInfoItem costPerKG;
    private GenericExtendedPropertyInfoItem density;
    private GenericExtendedPropertyInfoItem k;
    private GenericExtendedPropertyInfoItem shearStrength;
    private GenericExtendedPropertyInfoItem youngModulus;
    private GenericExtendedPropertyInfoItem n;
    private GenericExtendedPropertyInfoItem possionRatio;
    private GenericExtendedPropertyInfoItem hardness;
    private GenericExtendedPropertyInfoItem r;
    private GenericExtendedPropertyInfoItem materialCutCodeName;
    private GenericExtendedPropertyInfoItem name;
    private GenericExtendedPropertyInfoItem sourceName;
    private GenericExtendedPropertyInfoItem costUnits;
    private GenericExtendedPropertyInfoItem millingSpeed;
    private GenericExtendedPropertyInfoItem dataSource;
    private GenericExtendedPropertyInfoItem altName4;
    private GenericExtendedPropertyInfoItem costPerUnit;
    private GenericExtendedPropertyInfoItem altName5;
    private GenericExtendedPropertyInfoItem materialTypeName;
    private GenericExtendedPropertyInfoItem baseCostPerUnit;
    private GenericExtendedPropertyInfoItem process;
    private GenericExtendedPropertyInfoItem manufacturer;
    private GenericExtendedPropertyInfoItem tappedDensity;
    private GenericExtendedPropertyInfoItem maxPowderCycles;
    private GenericExtendedPropertyInfoItem recyclePercentage;
    private GenericExtendedPropertyInfoItem heatOfFusion;
    private GenericExtendedPropertyInfoItem solidusTemp;
    private GenericExtendedPropertyInfoItem specificHeatRT;
    private GenericExtendedPropertyInfoItem thermalConductivity;
    private GenericExtendedPropertyInfoItem squareBarCostPerUnit;
    private GenericExtendedPropertyInfoItem rectangularBarCostPerKG;
    private GenericExtendedPropertyInfoItem roundBarCostPerUnit;
    private GenericExtendedPropertyInfoItem angleBarCostPerUnit;
    private GenericExtendedPropertyInfoItem hexBarCostUnits;
    private GenericExtendedPropertyInfoItem tBeamCostUnits;
    private GenericExtendedPropertyInfoItem baseRoundBarCostPerUnit;
    private GenericExtendedPropertyInfoItem baseHexBarCostPerUnit;
    private GenericExtendedPropertyInfoItem rectangularBarCostUnits;
    private GenericExtendedPropertyInfoItem hexBarCostPerUnit;
    private GenericExtendedPropertyInfoItem roundBarCostPerKG;
    private GenericExtendedPropertyInfoItem baseTBeamCostPerUnit;
    private GenericExtendedPropertyInfoItem baseRectangularBarCostPerUnit;
    private GenericExtendedPropertyInfoItem baseSquareBarCostPerUnit;
    private GenericExtendedPropertyInfoItem tBeamCostPerKG;
    private GenericExtendedPropertyInfoItem roundTubeCostUnits;
    private GenericExtendedPropertyInfoItem baseSheetCostPerUnit;
    private GenericExtendedPropertyInfoItem squareBarCostPerKG;
    private GenericExtendedPropertyInfoItem rectangularTubeCostPerKG;
    private GenericExtendedPropertyInfoItem baseSquareTubeCostPerUnit;
    private GenericExtendedPropertyInfoItem roundTubeCostPerKG;
    private GenericExtendedPropertyInfoItem angleBarCostPerKG;
    private GenericExtendedPropertyInfoItem rectangularTubeCostUnits;
    private GenericExtendedPropertyInfoItem squareBarCostUnits;
    private GenericExtendedPropertyInfoItem sheetCostPerKG;
    private GenericExtendedPropertyInfoItem sheetCostUnits;
    private GenericExtendedPropertyInfoItem iBeamCostPerUnit;
    private GenericExtendedPropertyInfoItem iBeamCostUnits;
    private GenericExtendedPropertyInfoItem rectangularTubeCostPerUnit;
    private GenericExtendedPropertyInfoItem roundTubeCostPerUnit;
    private GenericExtendedPropertyInfoItem channelBarCostUnits;
    private GenericExtendedPropertyInfoItem angleBarCostUnits;
    private GenericExtendedPropertyInfoItem baseChannelBarCostPerUnit;
    private GenericExtendedPropertyInfoItem tBeamCostPerUnit;
    private GenericExtendedPropertyInfoItem channelBarCostPerKG;
    private GenericExtendedPropertyInfoItem iBeamCostPerKG;
    private GenericExtendedPropertyInfoItem rectangularBarCostPerUnit;
    private GenericExtendedPropertyInfoItem sheetCostPerUnit;
    private GenericExtendedPropertyInfoItem channelBarCostPerUnit;
    private GenericExtendedPropertyInfoItem roundBarCostUnits;
    private GenericExtendedPropertyInfoItem squareTubeCostPerKG;
    private GenericExtendedPropertyInfoItem baseRoundTubeCostPerUnit;
    private GenericExtendedPropertyInfoItem hexBarCostPerKG;
    private GenericExtendedPropertyInfoItem squareTubeCostUnits;
    private GenericExtendedPropertyInfoItem baseRectangularTubeCostPerUnit;
    private GenericExtendedPropertyInfoItem turningSpeed;
    private GenericExtendedPropertyInfoItem squareTubeCostPerUnit;
    private GenericExtendedPropertyInfoItem baseIBeamCostPerUnit;
    private GenericExtendedPropertyInfoItem baseAngleBarCostPerUnit;
}
